server:
  port: 8080
  
  servlet:
    context-path: /boot
  
spring:
  application:
    name: maven
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/xsh?serverTimezone=GMT
    username: root
    password: root
    
  servlet:
    multipart:
      enabled: true             #是否启用http上传处理
      max-request-size: 10MB    #最大请求文件的大小
      max-file-size: 2MB        #设置单个文件最大长度
      file-size-threshold: 1MB  #当文件达到多少时进行磁盘写入
      
  jackson:
    date-format: yyyy-MM-dd 
    time-zone: GMT+8
    
  mvc:
    view:
      prefix: /
      suffix: .jsp
      
mybatis:
  type-aliases-package: com.cssl.pojo
  mapper-locations: classpath:mapper/*.xml
  configuration:
    auto-mapping-behavior: full
    use-generated-keys: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    
pagehelper: 
  reasonable: true
  pageSizeZero: true
  helper-dialect: mysql
  support-methods-arguments: true
  params: countSql
